export const FILE_TRANSACTIONS ='FILE_TRANSACTIONS';
export const NEW_TRANSACTION ='NEW_TRANSACTION';
export const SEARCH_TRANSACTIONS ='SEARCH_TRANSACTIONS';
export const SORT_TRANSACTIONS ='SORT_TRANSACTIONS';

